name: S3 Deploy

on:
  release:
    types:
      - created
      
  workflow_dispatch:
env:
  AWS_REGION: ca-central-1
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'
    - run: flutter --version
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build web
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Sync to S3
      run: aws s3 sync . s3://csi5112project-frontend-bucket --delete --cache-control maxage=0 --acl public-read
      working-directory: ./build/web
    
    - name: Invalidate CloundFront Cache
      run: aws cloudfront create-invalidation --distribution-id ESEOCSDFLTZQF --paths "/*" 

 
